Add models to test-guru app
oozywaters/test-guru pull request #2
Opened 2018-02-26 12:17 UTC by oozywaters

Changes:

- Add test, question, answer, user, category models and migrations
- Add null constraints and default attributes (for tests and answers)

2018-02-26 18:46 UTC, iBublik requested changes

2018-02-26 18:46 UTC, iBublik commented on db/migrate/20180226095746_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
`index: true` можно опустить - в Rails 5 индексы в references создаются по умолчанию

2018-02-26 18:46 UTC, iBublik commented on db/migrate/20180226095746_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
Вообще странно, что у тебя эта миграция идет раньше, чем миграция создания категорий. Последовательно их выполнить невозможно - тут будет ошибка

2018-02-26 18:46 UTC, iBublik commented on db/migrate/20180226104831_create_answers.rb
> +    create_table :answers do |t|
А у ответов никакого текста нет?

2018-02-26 18:46 UTC, iBublik commented on db/migrate/20180226115958_add_users_null_constraints.rb
> +    change_column_null(:users, :username, false)
Чтоб не дублировать везде имя таблицы, можно воспользоваться методом [`change_table`](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_table) и внутри него методом `change`:
```ruby
change_table :users do |t|
  t.change :username, :string, null: false
  ...
end
```

2018-02-27 06:12 UTC, oozywaters commented on db/migrate/20180226095746_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
Мне тоже показалось это странным, но, как это ни удивительно, все миграции выполняются без ошибок)

2018-02-27 06:14 UTC, oozywaters commented on db/migrate/20180226115958_add_users_null_constraints.rb
> +    change_column_null(:users, :username, false)
Но в таком случае нам придется постоянно указывать тип атрибута, или есть метод аналогичный change_column_null?

2018-02-27 07:08 UTC, iBublik commented on db/migrate/20180226115958_add_users_null_constraints.rb
> +    change_column_null(:users, :username, false)
В доках не нашел

2018-02-27 07:10 UTC, iBublik commented on db/migrate/20180227055338_add_text_to_answers.rb
> +    change_column_null(:answers, :text, false)
Ты ведь строкой выше создаешь это колнку, сразу и укажи что у нее есть такой констрейнт - `add_column :answers, :text, :text, null: false`

2018-02-27 21:54 UTC, psylone approved these changes

2018-02-27 21:54 UTC, psylone commented on bin/rails
>  #!/usr/bin/env ruby2.3
В пулл-реквесте к заданию должно быть только то что непосредственно относится к заданию.

2018-02-27 21:54 UTC, psylone commented on config/application.rb
> -    config.time_zone = 'Moscow'
Зачем удалять настройки часового пояса и языка?

2018-02-28 05:37 UTC, merged