Rails models Lesson 4
oozywaters/test-guru pull request #3
Opened 2018-03-01 13:01 UTC by oozywaters

Changes:

- Add seed data
- Add join table for tests and users
- Add User and Test methods

2018-03-01 16:51 UTC, iBublik requested changes

2018-03-01 16:51 UTC, iBublik commented on app/models/test.rb
> +  has_and_belongs_to_many :users
Не рекомендую использовать `habtm`-связи. Они плохо расширяются (как только нужно будет дополнительные данные хранить, например счетчик связей или что-нибудь такое, сразу придется на `has_many :through` переделывать). 
К тому же, довольно трудно становится понять связи (без адекватного нейминга ассоциаций). Что за юзеры принадлежат тестам? Это пользователи, прошедшие тест? И что за пользователи владеют тестами? Это авторы тестов?

2018-03-01 16:51 UTC, iBublik commented on app/models/test.rb
> +  def self.tests_by_category(category)
Не нужно дублировать имя класса в имени метода

2018-03-01 16:51 UTC, iBublik commented on app/models/test.rb
> +      .order(:title)
Сортировка должна быть по убыванию

2018-03-01 16:51 UTC, iBublik commented on db/seeds.rb
> +                             ])
Тут можно использовать `index_by(&:title)`. Тогда при создании тестов было бы более понятно к какой категории они привязываются

2018-03-01 16:51 UTC, iBublik commented on db/seeds.rb
> +                             ])
Ну и при создании вопросов аналогично

2018-03-01 16:51 UTC, iBublik commented on db/seeds.rb
> +                      { title: 'Ruby', level: 1, category: categories[1] },
При извлечении из массива/хеша в таких ситуациях лучше использовать `fetch` - он упадет, если в коллекции нет нужного объекта. Позволит избежать ситуации, когда по какой-то причине категория не создалась

2018-03-01 16:53 UTC, iBublik commented on db/migrate/20180301110507_create_join_table_test_user.rb
> +      # t.index [:test_id, :user_id]
Индексы и внешние ключи на связи нужно создавать обязательно. Индексы ускорят поиск, а внешние ключи проследят за целостностью данных

2018-03-03 14:29 UTC, iBublik commented on app/models/test.rb
> +  has_many :tests_user
`has_many` ассоциации принято называть во множественном числе

2018-03-03 14:29 UTC, iBublik commented on db/migrate/20180301110507_create_join_table_test_user.rb
> +      t.references :user, index: true, null: false, foreign_key: true
`index: true` можно не указывать, он по умолчанию включен

2018-03-03 14:29 UTC, iBublik commented on db/migrate/20180301110507_create_join_table_test_user.rb
> +      t.references :test, index: true, null: false, foreign_key: true
Здесь индекс лишний, запрос `WHERE test_id = 1` сможет использовать комплексный индекс `[:test_id, :user_id]`
Много индексов - это тоже плохо, ведь они замедляют операции вставки/обновления

2018-03-03 14:29 UTC, iBublik commented on db/migrate/20180301110507_create_join_table_test_user.rb
> +    create_join_table :tests, :users do |t|
Теперь нет смысла использовать метод `create_join_table`, ведь ты по сути создаешь обычную таблицу. А в текущей у тебя нет id, нет таймстемпов (created_at/updated_at), что может помешать в будущем

2018-03-03 18:23 UTC, psylone approved these changes

2018-03-04 10:11 UTC, merged