App controllers
oozywaters/test-guru pull request #6
Opened 2018-03-16 16:53 UTC by oozywaters

Changes:

- Add questions list view
- Add question details view
- Add create question form
- Add destroy question method
- Add method callbacks to QuestionController
- Add exception handler for question not found

2018-03-17 11:06 UTC, iBublik requested changes

2018-03-17 11:06 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
Отделяй пустыми строками логические блоки кода.`before_action`-ы - это один блок, `rescue_from` - другой блок

2018-03-17 11:06 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    @question.answers << Answer.new(text: 'Yes', question: @question)
1. Ассоциации лучше создавать через `build` - `@question.answers.build(...)`
2. `<<` тут же производит сохранение в базу, так что эта строка сохранит и ответ, и вопрос
3. Зачем при создании вопроса создавать еще какой-то ответ к нему? В любом случае, это не логика контроллера. Чуть дальше мы пройдем как это делать правильно.

2018-03-17 11:06 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if @question.save!
Этот метод бросит исключение, если сохранение не удастся, так что if тут бессмысленный. Используй обычный `save`

2018-03-17 11:06 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(@question.test)
Стоит какое-то сообщение пользователю вывести, чтоб он понимал что удаление успешно прошло

2018-03-17 11:06 UTC, iBublik commented on app/controllers/questions_controller.rb
> +
Стоит описать экшн index, даже если у него будет пустое тело. Иначе получается очень неявно

2018-03-17 11:06 UTC, iBublik commented on app/views/questions/new.erb
> +<%= render :partial => 'form' %>
Просто `render 'form'`

2018-03-17 11:06 UTC, iBublik commented on app/views/questions/new.erb
> +<%= link_to 'Go Back', :test_questions %>
Впервые вижу, чтоб в link_to передавались символы. Так можно, да? 😄 
Непонятно как этот метод должен работать, ведь нам как минимум нужен инстанс теста, чтоб построить этот url

2018-03-18 13:46 UTC, iBublik reviewed
Лучше в шаблонах указывать формат конечного файла. Это поможет разработчику понять, что в итоге получится. Ведь erb используется не только для html, но и для простого текста. В общем, в имени шаблонов указывай `.html.erb`, а не просто `.erb`

2018-03-18 13:46 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    flash[:notice] = 'Question removed successfully'
Можно прямо в редиректе указывать notice-ы - `redirecto_to ..., notice: '...'`

2018-03-18 16:03 UTC, psylone approved these changes

2018-03-18 16:03 UTC, psylone commented on config/routes.rb
> +    resources :questions
`shallow: true` должна быть у ресурса вопросов.

2018-03-18 16:15 UTC, psylone approved these changes

2018-03-18 16:16 UTC, psylone approved these changes

2018-03-18 16:21 UTC, merged